spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: testemailfirst.testemaillast@gmail.com
    password: uebcuzagfbjzgqav
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  security:
    user:
      name: admin
      password: Password$1