spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: testemailfirst.testemaillast@gmail.com
    password: uebcuzagfbjzgqav
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true