spring:
  mail:
    host: smtp.gmail.com
    port: 587
#    username: your_email_id
#    password: your_password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 184949092335-datjduh5u1k29a5u4sd2kkpp7eu8v91i.apps.googleusercontent.com
            client-secret: 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
