spring:
  config:
    import: optional:secrets.yml
  mail:
    host: smtp.gmail.com
    port: 587
#    username: your_email_id
#    password: your_password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: your-client_id
#            client-secret: your_client_secret